set_property SRC_FILE_INFO {cfile:{C:/Users/zhang/Documents/Computer Architecture/ComputerArch2019/RISCV_CPU/RISCV_CPU.srcs/constrs_1/imports/src/Basys-3-Master.xdc} rfile:../../../RISCV_CPU.srcs/constrs_1/imports/src/Basys-3-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports EXCLK]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports led]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btnC]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports Rx]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports Tx]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list EXCLK_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 31 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpu0/pc_reg0/npc0[0]} {cpu0/pc_reg0/npc0[1]} {cpu0/pc_reg0/npc0[2]} {cpu0/pc_reg0/npc0[3]} {cpu0/pc_reg0/npc0[4]} {cpu0/pc_reg0/npc0[5]} {cpu0/pc_reg0/npc0[6]} {cpu0/pc_reg0/npc0[7]} {cpu0/pc_reg0/npc0[8]} {cpu0/pc_reg0/npc0[9]} {cpu0/pc_reg0/npc0[10]} {cpu0/pc_reg0/npc0[11]} {cpu0/pc_reg0/npc0[12]} {cpu0/pc_reg0/npc0[13]} {cpu0/pc_reg0/npc0[14]} {cpu0/pc_reg0/npc0[15]} {cpu0/pc_reg0/npc0[16]} {cpu0/pc_reg0/npc0[17]} {cpu0/pc_reg0/npc0[18]} {cpu0/pc_reg0/npc0[19]} {cpu0/pc_reg0/npc0[20]} {cpu0/pc_reg0/npc0[21]} {cpu0/pc_reg0/npc0[22]} {cpu0/pc_reg0/npc0[23]} {cpu0/pc_reg0/npc0[24]} {cpu0/pc_reg0/npc0[25]} {cpu0/pc_reg0/npc0[26]} {cpu0/pc_reg0/npc0[27]} {cpu0/pc_reg0/npc0[28]} {cpu0/pc_reg0/npc0[29]} {cpu0/pc_reg0/npc0[30]}]]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpu0/if0/_inst[0]} {cpu0/if0/_inst[1]} {cpu0/if0/_inst[2]} {cpu0/if0/_inst[3]} {cpu0/if0/_inst[4]} {cpu0/if0/_inst[5]} {cpu0/if0/_inst[6]} {cpu0/if0/_inst[7]} {cpu0/if0/_inst[8]} {cpu0/if0/_inst[9]} {cpu0/if0/_inst[10]} {cpu0/if0/_inst[11]} {cpu0/if0/_inst[12]} {cpu0/if0/_inst[13]} {cpu0/if0/_inst[14]} {cpu0/if0/_inst[15]} {cpu0/if0/_inst[16]} {cpu0/if0/_inst[17]} {cpu0/if0/_inst[18]} {cpu0/if0/_inst[19]} {cpu0/if0/_inst[20]} {cpu0/if0/_inst[21]} {cpu0/if0/_inst[22]} {cpu0/if0/_inst[23]} {cpu0/if0/_inst[24]} {cpu0/if0/_inst[25]} {cpu0/if0/_inst[26]} {cpu0/if0/_inst[27]} {cpu0/if0/_inst[28]} {cpu0/if0/_inst[29]} {cpu0/if0/_inst[30]} {cpu0/if0/_inst[31]}]]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets EXCLK_IBUF_BUFG]
